/* Generated Insert Queries */
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `units`;
TRUNCATE TABLE `device_users`;

/* Units */
INSERT INTO `units` (`name`) VALUES ('KLINIK GIGI');
INSERT INTO `units` (`name`) VALUES ('KLINIK KANDUNGAN');
INSERT INTO `units` (`name`) VALUES ('KLINIK SARAF');
INSERT INTO `units` (`name`) VALUES ('KLINIK ANAK');
INSERT INTO `units` (`name`) VALUES ('KLINIK UMUM');
INSERT INTO `units` (`name`) VALUES ('KLINIK PARU');
INSERT INTO `units` (`name`) VALUES ('KLINIK MCU');
INSERT INTO `units` (`name`) VALUES ('KLINIK PENYAKIT DALAM');
INSERT INTO `units` (`name`) VALUES ('KLINIK BEDAH UMUM');
INSERT INTO `units` (`name`) VALUES ('KLINIK BEDAH TULANG');
INSERT INTO `units` (`name`) VALUES ('IGD KEBIDANAN');
INSERT INTO `units` (`name`) VALUES ('IGD');
INSERT INTO `units` (`name`) VALUES ('REHABILITASI MEDIS');
INSERT INTO `units` (`name`) VALUES ('HEMODIALISA');
INSERT INTO `units` (`name`) VALUES ('KLINIK GIZI');
INSERT INTO `units` (`name`) VALUES ('TULIP');
INSERT INTO `units` (`name`) VALUES ('TERATAI');
INSERT INTO `units` (`name`) VALUES ('LILY');
INSERT INTO `units` (`name`) VALUES ('CATELYA');
INSERT INTO `units` (`name`) VALUES ('ICU');
INSERT INTO `units` (`name`) VALUES ('KLINIK THT');
INSERT INTO `units` (`name`) VALUES ('KLINIK JIWA');
INSERT INTO `units` (`name`) VALUES ('KLINIK VCT');
INSERT INTO `units` (`name`) VALUES ('KLINIK COVID 19');
INSERT INTO `units` (`name`) VALUES ('ISOLASI TERATAI');
INSERT INTO `units` (`name`) VALUES ('ISOLASI TULIP');
INSERT INTO `units` (`name`) VALUES ('KLINIK JANTUNG');
INSERT INTO `units` (`name`) VALUES ('KLINIK VAKSINASI');
INSERT INTO `units` (`name`) VALUES ('KLINIK GIGI BEDAH MULUT');
INSERT INTO `units` (`name`) VALUES ('IGD COVID');
INSERT INTO `units` (`name`) VALUES ('ICU COVID');
INSERT INTO `units` (`name`) VALUES ('KLINIK MATA');
INSERT INTO `units` (`name`) VALUES ('PERINATALOGI');
INSERT INTO `units` (`name`) VALUES ('DEPO RAWAT JALAN');
INSERT INTO `units` (`name`) VALUES ('KLINIK GIGI PENYAKIT MULUT');
INSERT INTO `units` (`name`) VALUES ('REKAM MEDIS');
INSERT INTO `units` (`name`) VALUES ('GUDANG RM');
INSERT INTO `units` (`name`) VALUES ('Depo RI');
INSERT INTO `units` (`name`) VALUES ('Depo IGD');
INSERT INTO `units` (`name`) VALUES ('Gudang Farmasi');
INSERT INTO `units` (`name`) VALUES ('VK');
INSERT INTO `units` (`name`) VALUES ('BPJS');
INSERT INTO `units` (`name`) VALUES ('NIFAS');
INSERT INTO `units` (`name`) VALUES ('OK');
INSERT INTO `units` (`name`) VALUES ('LOKET PENDAFTARAN');
INSERT INTO `units` (`name`) VALUES ('RADIOLOGI');
INSERT INTO `units` (`name`) VALUES ('LABORATORIUM');
INSERT INTO `units` (`name`) VALUES ('KLINIK ORTOPEDI');
INSERT INTO `units` (`name`) VALUES ('KLINIK GINJAL HIPERTENSI');
INSERT INTO `units` (`name`) VALUES ('KLINIK PENYAKIT DALAM 2');

/* Device Users */
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ratna', 'Ratna Pindarwati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('desi', 'Desi Heriyani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('zainur', 'Zainur Rahmah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('arfiani', 'Arfiani Arsyad');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurul', 'Nurul Yustiningsih, S.Sos');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aminarti', 'Aminartiana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('eni', 'Eni Fitriani, A.Md.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurdiani', 'Nurdiani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dayah', 'Hidayah Purnama, S.KM');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mulki', 'Mulkiyana Samsul');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rico', 'Rico Setiadi Pratama');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mika', 'Mika Restuty, A.Md.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('david', 'MUHAMMAD DAVID');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ridho', 'RIDHO AKHMAD AL RASYID');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sartina', 'Sartina, S.Kep. Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('purwatii', 'Purwati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('serinah', 'Serinah, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endangapriyani', 'Endang Apriyani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('juli', 'Juli, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ribur', 'Ribur HS Hutagalung, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('isnipatria', 'Isni Patria, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sitinurasiah', 'Siti Nurasiah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andifachrul', 'Andi Fachrul Pangerang');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('veny', 'Veny Yusnica');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andirosmini', 'Andi Rosmini Madjid, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fisio', 'dr. Wicaksono A. Budihartanto, M.Ked.Klin, Sp.KFR');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hugo', 'dr. Hugo Dwiputra W');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ricky', 'dr. Ricky Gunawan, Sp.N');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fisioterapi', 'dr. Wicaksono A. Budihartanto, M.Ked.Klin, Sp.KFR');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yenny', 'dr. Yenny Transiska, Sp. P');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ita', 'dr. Ita Haryatie, Sp.P, M.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('astri', 'drg. Astri Kusumawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ainun', 'drg. A. Ainun Mardiyah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nura', 'drg. Nurul Azizah Ali');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('silfra', 'drg. Silfra Yunus Kende, Sp.PM');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asnani', 'Asnani, A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aidil', 'Aidil, A.Md.Kg');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('akhsanal', 'drg. Akhsanal Fauzi, Sp.BM');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hery', 'dr. Hery Setiawan, Sp.B');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anang', 'dr. Anang Auric Yuliandar, Sp.B');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('farah', 'dr. Farah Katleya Cendikiana, Sp.A');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asriani', 'dr. Andi Asriani Arif, Sp. KJ');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ketut', 'dr. Ketut Widaya, Sp.OG');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fujiyanto', 'dr. Fujiyanto Sp.OG');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mahdalena', 'Mahdalena');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurhayati', 'Nurhayati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurhasyanah', 'Nurhasyanah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nana', 'nana marliana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anita', 'Anita Astiana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('Hanan', 'Isbath Zaini');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nonaktif', 'Isbath Zaini');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('harlina', 'Harlina, A.Md');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('herda', 'Rahayu Herda Indriyani, A.Md.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('richa', 'dr. Richa Endah Prawesti, Sp. T.H.T.K.L');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('faizin', 'dr. Faizin. Sp.JP');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andi_ashaq', 'dr. Andi Ashaq');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ony', 'dr. Ony Wiraswati, Sp.PD');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('farid', 'dr. Muh Dinul Fazmar Farid, Sp.PD');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('admisi', 'Harlina, A.Md');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('HARPIANI', 'HARPIANI');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ulfaqq', 'Ulfaiyah, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('kennytha', 'dr. Kennytha Yoesdyanto');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yohanes', 'dr. Yohanis Timang, Sp.OG');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('bie', 'Sabbi Hisma, A.Md.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('novitasari', 'novitasari, A.Md.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('misnawati', 'Misnawati, S.Keb,Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('alisa', 'Alisa');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('stella', 'dr. Stella');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('stella', 'dr. Stella');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('febriana', 'Febriana Shoan Perdani, A.Md');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('kartina', 'Kartinah Purwandani, A.Md.RMIK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('norma', 'Norma Widharti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rahmawati', 'Rahmawati, A.Md. Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nourma', 'Nourma Baity Furqony');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sitti', 'Sitti Ramlah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tesa', 'Tesa Gita Susanti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('juniar', 'Juniar');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lena', 'Lena Erliana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('maulidal', 'Maulidal Hasanah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('azzahrah', 'Azzahrah Bulkis');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('kasmawati', 'Kasmawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nina', 'Nina Oktavia');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fitriani', 'Fitriani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('agnes', 'Agnes Stefanie');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('heru', 'Heru Guswanto');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('munawir', 'Munawir, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hilyatul', 'Ns. Hilyatul Husna, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ekawahyuni', 'Eka Wahyuni Natalia, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('suheny', 'Suheny, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ratnadewi', 'Ratna Dewi Marini, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yultha', 'Yultha Nice Rumengan, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('arinurgita', 'Ari Nurgita, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endangz', 'Endang Zubaidah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('satriana', 'Satriana, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('alfianindra', 'Ns. Alfian Indra Wijaya, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jumanah', 'Jumanah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mariadesi', 'Ns. Maria Desi, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lukmaneffendi', 'Ns. Lukman Effendi, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('very', 'Very Bilyardani, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rima', 'Rima Selviana, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nuruls', 'Nurul Sakinah, S.E');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nsrahman', 'Ns.Rahman Junaedi,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('irni', 'Irni Yusnita, S.Keb.Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('salamah', 'Tsalatsiatus salamah,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sriulandari', 'Ns. Sri Ulandari, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('triprasetya', 'Tri Prasetya Rahayu, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jorianto', 'dr. Jorianto Muntari, Sp.PD');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ayunur', 'Ayu Nur Alisa');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rumiati', 'Rumiati, S,Kep,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('waodefd', 'Wa Ode Fitria Dahlan, SE');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hikmawati123', 'Hikmawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ekasetiawati', 'Eka Setia Wati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anmal', 'Sanawiyah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('devina', 'dr. Devina Carolina Mastari');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andihasriani', 'Andi Hasriani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurulhda', 'Nurul Huda');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('herys', 'Hery Sulisdiyanto, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('PURNAMASARI', 'ITA PURNAMASARI');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hermin', 'Hermin Limbu,A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nining', 'Nining');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nursam', 'Nursam');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rosdiana', 'Rosdiana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andiyuli', 'Andi Yuli');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('idhang', 'Muhammad Idhang, Sst.FT, Ftr');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('wicaksono', 'dr. Wicaksono A. Budihartanto, M.Ked.Klin, Sp.KFR');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asihsuprihatin', 'Asih Suprihatin, AMF');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hestygayatri', 'Hesti Gayatri Sari, Amd.Fis');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mariarante', 'Maria Rante, Amd.FT');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('harisali', 'Muhammad Haris Ali Faqih, Amd.FT');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('musdalifah', 'Musdalifah Nur,S.Ft.,Ftr');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adhina', 'Adhina Nur Fajrin, S.tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('Sizka', 'Sizka Noerima, S.I.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drumi', 'dr. Umi Salamah,M.Ked. Klin, Sp.MK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drasru', 'dr. Asrussanah, Sp.PK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dremi', 'dr. Emi Setianingsih,Sp.PK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drworo', 'dr. Woro Dwi Astuti,Sp.PA');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drsanti', 'dr. Santi Maulina, Sp.PA');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ronipri', 'Roni Prianggawan, S.Tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('Sayid Arifin', 'Sayid Arifin. S .S. T, M.M.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('masliana', 'Masliana, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ronyjun', 'Rony Junaedi, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurulhidayah', 'Nurul Hidayah, S.Tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mamisulis', 'Mami Sulistiawati, AMd.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('wiwi', 'Suparwi, S.Tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ifitmaha', 'Ifit Mahananik, S.Tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('atikadwi', 'Atika Dwi Y, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('husnulcho', 'Husnul Chotimah, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ununnur', 'Unun Nurhasanah, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endahwulan', 'Endah Wulandari, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('JuwitA', 'Juwita Puspita Sari Lilis Ramadanie, S.Tr.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tikasuci', 'Tika Suci Ramadani, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('martaabi', 'Marta Abigael Manalu, AMd. Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ahmadyadi', 'Ahmad Yadi, AMd. AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ekdewi', 'E K Dewi');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nonaktif2', 'Isbath Zaini');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('misfahyus', 'Misfah Yustina');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asaiful', 'Ahmad saiful');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('evinusriati', 'Evi Nusriati Soleha,A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('kathleen', 'dr Kathleen Vaalentina Kawilarang');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hikmawatiper', 'Hikmawati, Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('maharaniasma', 'Maharani Asma M S, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('janur', 'dr. Janur Putri Kinanti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('foraldy', 'dr. Jeffry Foraldy Haryanto');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hanifahd', 'Hanifah D,A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('agustinaa', 'Agustina A.Md.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('elbert', 'dr. Elbert Wiradarma');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yulianti', 'Yulianti, A.Md');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ferdinando', 'dr. Ferdinando Kaose, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('widyhelen', 'dr. Widy Helen, Sp.PD, FINASIM');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rosdianabpjs', 'Rosdiana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurhasyanah2', 'NURHASYANAH');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anselpina', 'ANSELPINA DUA SOKA');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erwin', 'dr. Erwin Widi Nugraha');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drjohanes', 'dr. Johanes Pratama Suyono');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('firani', 'FIRANI FIRMAN');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('setiawann', 'dr. Setiawan Sulisthio');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ridwano', 'Ridwan');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nahrifah', 'Nurul Nahrifah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dafa', 'Daffa Fatir Rizky');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nonaktif', 'Isbath Zaini');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andrini', 'Patricia Andrini Panjaitan, S.Akun');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('drnovita', 'dr. Novita Rosana, M.Kes (MARS)');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yudiani', 'Yudiani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rukma', 'apt. Ruk''at Rukmayanti, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('melia', 'apt. Melia Mulyani, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('purwanica', 'apt. Purwanica Sutimin, S.Si');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('retnosusilo', 'Retno Susilo, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('primas', 'Primas Wardhani Adhya N., A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sugiarto', 'sugiarto');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('abdulkarim', 'Abdul Karim');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('bintoro', 'apt. Bintoro Hadi Winaryo, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('Soleman', 'Soleman Tampang, S.Si.Apt');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('audi', 'Audi Marthen, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jenny', 'Jenny Tri Sekawati Payuk, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adeimelda', 'Ade Imelda Rantias. A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('suwandi', 'Suwandi, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fitriyanti', 'Fitri Yanti, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('armanj', 'Arman J');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('histiqomah', 'Histiqomah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('renin', 'Reni Nuramayani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('herman', 'apt. Herman Effendi, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('zulfahmi', 'Zulfahmi, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nuraini', 'Nuraini Manurung, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lilik', 'Lilik Dina Lestari, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rezaf', 'Muhammad Reza Firdaus, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nabilafarmasi', 'Nabila');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asti', 'Asti Pranita, S.Farm.Apt');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('swenny', 'Swenny Ningsih, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sunarti', 'Sunarti, S.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aptyudhi', 'apt. Yudhi Setya Kurniawan, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('firna', 'Firna Astuti, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jihanfarm', 'Jihan Aprilia, A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('megawatifar', 'Megawati, A.Md.Far');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurasia', 'Nurasia, S.Si');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('simanjuntak', 'Simanjuntak Yuni Kristina. A.Md.Farm');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andriana', 'Andriana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endah', 'Endah Monita Sari');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lukasiwan', 'dr. Lukasiwan Eddy Saputro, MM.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adamkristy', 'dr. Adam Kristy');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('afdelina', 'dr. Afdelina Rizky A');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andiashaq', 'dr. Andi Ashaq');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anindita', 'dr. Anindita Muslimah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('daniel', 'dr. Daniel Sitinjak');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('deseli', 'dr. Deseli Eka Rahmawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dewipurnama', 'dr. Dewi Purnama Sari');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dewisusanti', 'dr. Dewi Susanti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('indahdwi', 'dr. Indah Dwi Hari, F.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jelijati', 'dr. Jeli Jati Anggeria');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurjannah', 'dr. Nur Jannah Khairunnisa');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurulfahmi', 'dr. Nurul Fahmi');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rulli', 'dr. Rulli Sibarani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('septiani', 'dr. Septiani Kusumaningtyas');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('siscaandriany', 'dr. Sisca Andriany');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('syahroni', 'dr. Syahroni');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yenyangdriani', 'dr. Yeny Angdriani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lahuda', 'dr. Lahuda Adjinegoro, Sp.B., M.Ked.Klin');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('robinson', 'dr. Robinson Manurung, Sp.PD-KGH');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('bagusputra', 'dr. Bagus Putra Dharma Khrisna, Sp.JP');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('enawati', 'Enawati, Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('william', 'dr. William');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('abdurrazzaq', 'dr. Abdur Razzaq');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('edwinkasmun', 'dr. Edwin Kasmun');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rezqy', 'Rezqy Annisa Febrianty');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('octaviana', 'Apt. Octaviana Maria Simbolon, S.Farm, M.Farm.Klin');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yudhisetya', 'apt. Yudhi Setya Kurniawan, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('Youstantri', 'apt. Youstantri Pongleppan, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aptnadya', 'apt. Nadya Tri Lestari, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yosua', 'dr. Yosua Adi Nugroho, Sp.OT, FICS');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dian', 'dr. Robinson Manurung, Sp.PD-KGH');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('evy', 'dr. Evy Irmawaty Apidian, Sp.M');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('alfiani', 'Ramadhan Noor Alfiani, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('syhar', 'Siti Hariati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mayriza', 'Mayriza Wulandari, AMG');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jihankartika', 'Jihan Kartikarani, S.Tr.Gz');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mayaamalia', 'Maya Amalia Sugiarto, S.Gz');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('friska', 'Friska Widiastuti, A.Md.Gz');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('marliyanti', 'Marliyanti Patanduk, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('isnipatria', 'Isni Patria, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ribur', 'Ribur HS Hutagalung, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('susiyati', 'Susiyati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rinairiana', 'Rina Iriana, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('herawati', 'Herawati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gerhana', 'Gerhana, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('chintya', 'Chintia Adelina Pramita, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sangaji', 'Sangaji Putra, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('purwati', 'Purwati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ekamina', 'Eka Minawati, A.Md. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ruwi', 'dr. Ruwiyatul Aliyah, Sp.GK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aptkiki', 'apt. Kiki Nurhasanah, S.Farm.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('spj', 'SPJ');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('timothy', 'dr. Timothy Alexander Liwang');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ludfi', 'Ludfi Hardini, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dinurrohmah', 'Dina Dinurrohmah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dr.AbdulHaris', 'dr. Abdul Haris, M. Kes., Sp.Rad');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dr.Novie', 'dr. Novie Daninda Indrari, Sp. Rad');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tresmi', 'Tresmi, A.Md.AK');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ayupuspita', 'Ayu Puspita Fitriani, A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rezaokta', 'Reza Oktaviana Syahputri,  A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nahriabili', 'Nahria Bili,  A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endangrahayu', 'Endang Rahayu, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mulkayana', 'Mulkayana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurbayah', 'Nurbayah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('admisites', 'Rico Setiadi Pratama');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adventri', 'Adventri Tulak Siagian, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jumrah', 'Jumrah Reski, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yusmeini', 'Yusmeini, S.Kep.Ns.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('susanti', 'Susanti Anggraini, S.Kep.Ns.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sigit', 'Sigit Santoso, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adeirma', 'Ns. Ade Irma Ichtyana,S.kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tutihandayani', 'Tuti Handayani, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('priyo', 'Priyo Multiadi Meikrisno, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('raniyulianti', 'Rani Yulianti, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurjanah', 'Nurjanah, S.Kep,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tamrizal', 'Tamrizal AM, M.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anisah', 'Anisah, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yunus', 'M.yunus,A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('waode', 'Waode Fitriah Dahlan, S.E');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('beriyan', 'dr. Lalu Beriyan Berjid Ardani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rabiatul', 'Rabiatul Gusmiah, S.Keb.Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tukini', 'Tukini Andriani, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tukini', 'Tukini Andriani, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fitria', 'Fitria Herawati, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fitriani', 'Fitriani, A.Md.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ritafebriani', 'Rita Febriani, S.Tr.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hardianti', 'Hardianti AM, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andianita', 'Andi Anita Safitri Ramadani, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rahmatan', 'Rahmatan, S.Keb.Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rodiatul', 'Rodiatul Mahdiah, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gracehanna', 'Grace Hanna, S.Tr.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hamidasst', 'Hamidah, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anilia', 'Anilia Hidayati, S.S.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('aminamd', 'M.Amin,A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rosaria', 'Rosaria Endang S,S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dwiki', 'Muhammad Dwiki Darmawan, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ridha', 'Mohammad Ridha Alfian Noor, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('srihariati', 'Sri Hariati, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('bayumustiko', 'Bayu Mustiko,A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lusiana', 'Lusiana, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('emir', 'Emir M,A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('winarti', 'Winarti A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sulpandi', 'Sulpandi, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hardiyanti', 'Siti Hardianti, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rickyihsan', 'Ns,Ricky Ihsan Nanda,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('miftahul', 'Miftahul Khair, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('heriyati', 'Heriyati, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('windra', 'Windra S,A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('elyanus', 'Elyanus Patira, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurun', 'Nurun Hikmah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hermanper', 'Herman Flani, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erwinok', 'Ns,Erwin,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tutihandayani', 'Tuti Handayani, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dibyo', 'dr. Evy Irmawaty Apidian, Sp.M');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anywidya', 'Any Widyastuti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('faisal', 'Faisal');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yuliawati', 'dr. Yuliawati, Sp.A');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('abdullahpatria', 'dr. Abdullah Patria N');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('NiningYuda', 'Nining Yuda Timur Yanti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jumria', 'dr. Jumria Tandi Panggalo, Sp.PD');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('prayogi', 'dr. Muh. Prayogi A-Syah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('masriah', 'Masriah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rifki', 'Muhammad Rifki');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('syahroni', 'dr. Syahroni Sp.F.M');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hikmawati', 'Hikmawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('husna', 'Husna Ayu');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ragil', 'Ragil Irwansyah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sisca', 'dr. Sisca Andriany');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anindita', 'dr. Anindita Muslimah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('anggitya', 'Anggitya Dita Wahyuningsih, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('arie', 'Arie Triani, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('irawan', 'Ns.Adi Irawan S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adma', 'Ns.Adma Widyasari,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asniyati', 'Asniyati,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('darmawati', 'Ns. Darmawati, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('desiroikah', 'Desi Roikah,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ester', 'Ester Yulan Marcelina,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fransiska', 'Ns. Fransiska Ribu, S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hendro', 'Hendro Sunarto,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lini', 'Lini Puspita Sari, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('lutvi', 'Ns.Lutvi Dhika N,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mayaaulia', 'Maya Aulia Dwi Hafsari, S.Tr.Keb, Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('miftahuljannah', 'Miftahul Jannah, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('monica', 'Monica Pratiwi H,Amd.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('firdaus', 'Ns.Muhammad Firdaus,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yusuf', 'Muhammad Yusuf,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('muttiara', 'Muttiara, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('novipieter', 'Novi Pieter Biri,Amd.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('budiansyah', 'Ns.Budiansyah,s.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gaguk', 'Ns.Gaguk Sulistiawan,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sakti', 'Ns.Sakti Wadhi Nurmey,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurulandriani', 'Nurul Andriani,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rahman', 'Ns.Rahman Junaedi,S.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('raudhatun', 'Raudhatun Nisa,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('riarusdiana', 'Ria Rusdiana, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rosdianaigd', 'Rosdiana,Amd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('suci', 'Suci Sustiani, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('wiwik', 'Wiwik Lestari, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('zayyin', 'Apt. Zayyin Wardiah, S.Farm.,');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rjannah', 'Raudhatul Jannah, S.Tr.Gz');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('omy', 'Rosmiati Nur, A.Md.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('romy', 'dr. Romy Media Irianto, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('faozi', 'dr. Ahmad Faozi, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ulfa', 'Ulfa Ani Zahroh');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ferdinando', 'dr. Ferdinando Kaose, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ferdinando', 'dr. Ferdinando Kaose, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ferdinando', 'dr. Ferdinando Kaose, Sp.An');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mike', 'dr. Mike Christanti, Sp.PD');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('prayoga', 'dr. I Putu Prayoga Tenaya');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('endahsusanti', 'Endah Susanti Novitasari, Amd. Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('apm3', 'Rosmiati Nur, A.Md.Kom');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dewiaks', 'Dewi Anggraini Kartika Sari, A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('yuliana', 'Yuliana');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('niningsafitri', 'Nining Safitri');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fajrin', 'Muh. Fajrin');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fitriaherawati', 'Fitria Herawati, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tukini', 'Tukini Andriani, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('bunga', 'Bunga Ayu Frepitasari, S.Tr.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rahmatan', 'Rahmatan, S.Keb.Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rabiatul', 'Rabiatul Gusmiah, S.Keb.Bdn');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rinaeka', 'Rina Ekawati, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gracehanna', 'Grace Hanna, S.Tr.keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('megawatipurba', 'Megawati Purba, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('irpanah', 'Irpanah Angga Dwi Wahyuni, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ritafebriani', 'Rita Febriani, S.Tr.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hamidah', 'Hamidah, S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('cipta', 'dr. A. Karwana Cipta Sulfikar');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dina', 'Dina, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sridevi', 'Sri Devi');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('husni', 'Husni, A.Md.Kes');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jumasliani', 'Jumasliani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('jurniati', 'Jurniati, A.Md');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('tutut', 'Tutut Purwanti, M.Si');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mamik', 'Mamik Hidayati,S.ST');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('risda', 'Risda Emilia, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('linda', 'Linda, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dewiam', 'Dewi Anggreani Muntholib, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('isnawati', 'Isnawati, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erni', 'Erni Agustina Nadeak, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ana', 'Ana Kurnia Sari, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurulf', 'Nurul Fakhrani, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('arindi', 'Arindi Sulistiani, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dorkas', 'Dorkas Amon, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('herliana', 'Herliana Waty, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ary', 'Ary Novitasari, S.Kep.Ns.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erlis', 'Erlis Sumarni, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nurlaelah', 'Nurlaelah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andimka', 'Andi Muhammad Khaerun Amin, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sulistini', 'Sulistini, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('asmah', 'Asmah Yunita Amin, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hamidah', 'Sitti Hamidah, AMd.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nuruli', 'Nurul Istiqomah, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gita', 'Nur Gita Rahanjani, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dewir', 'Dewi Rachmawati');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('puput', 'Puput Susanti, SH');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rochmana', 'Aulia Widya Rochmana, S.Tr.Kep.,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('fengki', 'Fengki Ayu Lestari, S.kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erma', 'Ade Erma Itcayana, S. Kep, Ners');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nuryatin', 'Reny Nuryatin Asni, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rayfiska', 'Rayfiska Rahayu, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('adwianty', 'Adwianty Barra, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('marlaeni', 'Marlaeni, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('warinah', 'Warinah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('erlian', 'Erlian, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('qomariah', 'Nur Qomariah');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('candra', 'Candra Hapsari Rahmawati, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('wilshin', 'Wilshinsiani Aprilidis Gloria N, S.Kep,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('wiwin', 'Wiwin Subekti, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('rosidah', 'Khalifatul Rosidah, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hapsah', 'Siti Hapsah, S.Kep.,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('sthardianti', 'Siti Hardianti, S.Kep, Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('dailva', 'Vina Sylviana Dailva, A.Md.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('setiawan', 'Budi Setiawan, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('devipuspita', 'Devi Puspita Sari, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mahyu', 'Mahyu Eka Chandra, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('kristinawati', 'Ayu Kristinawati, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('nursafitri', 'Evi Nur Safitri, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('isla', 'Islamuddin, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('hartiva', 'Hartiva Lattang, S.Kep.,Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('etty', 'Etty Nur Bayani, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('trida', 'Trida Sanda, A.Md. Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('andina', 'Andina Fajar Oktaria, S.Tr.Keb');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('heraa', 'Herawati, A.Md.Kep');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('evasusanti', 'Eva Susanti');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('elis', 'Elis Fitriani');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('juliana', 'Juliana, S.Kep.Ns.');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('helmina', 'Helmina, S.Kep.Ns');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('franata', 'dr. Dodi Franata, Sp.An-TI');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('user_dev_tmp', 'dr. Bagus Putra Dharma Khrisna, Sp.JP');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('gustiayu', 'dr. Ni Gusti Ayu Pitria Sepstiani, Sp.An-TI');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('ronal', 'Muhammad Adrian Ronaldy');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('mufti', 'dr. Mufti Akhmad Shadiq');
INSERT INTO `device_users` (`name`, `full_name`) VALUES ('finda', 'dr. Finda Rahmanisa');

SET FOREIGN_KEY_CHECKS = 1;